spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes: #?? ??? ??? ??
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/auth/**,/user/**
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/book/**,/booklike/**
      default-filters:
        - name: JwtAuthFilter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
