#spring.application.name=2nd-backend
spring:
  datasource:
    url: jdbc:mariadb://dev.macacolabs.site:3306/readwedb
    username: readwe
    password: readwe
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  #Redis 설정자리
#  data:
#    redis:
#      host:
#        port:

jwt:
  secret: aVeryLongAndSecureSecretKeyForHS256AlgorithmThatMustBeAtLeast32Bytes